# Generated by Django 3.1.5 on 2021-01-18 20:05

from django.db import migrations, models


def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "settings")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RunPython(load_stores_from_fixture)
    ]
